dist: xenial


language: python


compiler: g++


python:
  - 3.6


env:
  global:
    - TRAVIS_CI=true
    - PYTHONPATH=$(pwd)
    - COVERAGE_PROCESS_START="$(pwd)/tox.ini"


cache:
  directories:
    - $HOME/.cache/pip


jobs:
  include:
    - stage: "Tests"
      name: "Lint"
      install:
        - pip install flake8
      script:
        - make lint-local

    - name: "pipenv check"
      install:
        - pip install pipenv
      script:
        # `pipenv check` is occasionally flaky and depends on network connectivity,
        # so try up to 3 times, waiting 60 seconds between tries
        - pipenv check || (sleep 60; pipenv check) || (sleep 60; pipenv check)

    - name: "black check"
      install:
        - pip install black
      script:
        - make black-check-local

    - name: "Unit Tests"
      before_script:
        - ulimit -c unlimited -S       # enable core dumps
      install:
        - pip install pipenv codecov
        - pip install typed_python==0.1.1
        - pipenv lock --dev --requirements > dev-reqs.txt
        - pip install --requirement dev-reqs.txt
        - pip install --editable .  # install object_database in 'editable' form.
        - sudo apt-get install --assume-yes gdb  # install gdb
        - make testcert.cert
      script:
        - coverage erase
        - pytest
        - ls -la
        - coverage combine
      after_success:
        - codecov
      after_failure:
        - PYTHON_EXECUTABLE=$(python3 -c "import sys; print(sys.executable)")
        - COREFILE=$(find . -maxdepth 1 -name "core*" | head -n 1) # find core file
        - if [[ -f "$COREFILE" ]]; then
              gdb -c "$COREFILE" $PYTHON_EXECUTABLE -ex "thread apply all bt" -ex "set pagination 0" -batch;
          fi
