[build-system]
# require numpy 1.20 to support python 3.6
requires = [
    "setuptools",
    "wheel",
    'oldest-supported-numpy',
    'typed_python >= 0.2.4'
]
# build-backend = "setuptools.build_meta:__legacy__"
