[build-system]
# require numpy 1.20 to support python 3.6
requires = [
    "setuptools",
    "wheel",
    "numpy < 1.20",
    "typed_python @ git+https://github.com/aprioriinvestments/typed_python.git@b388f21afc877867dfcdfac74f9b0f9d27816e92#egg=typed_python-999.999.999"
]
