[build-system]
# require numpy 1.20 to support python 3.6
requires = [
    "setuptools",
    "wheel",
    "numpy < 1.20",
    "typed_python @ git+https://github.com/aprioriinvestments/typed_python.git@f72071b62e96ed25b7b6e6771d25bcbd0385c695#egg=typed_python-999.999.999"
]
