[build-system]
requires = [
    "setuptools",
    "wheel",
    "numpy",
    "typed_python @ git+https://github.com/aprioriinvestments/typed_python.git@4cfb5315b9db6b4cedd35188617abe0b48f7eedc#egg=typed_python-999.999.999"
]
