[build-system]
requires = [
    "setuptools",
    "wheel",
    "numpy",
    "typed_python @ git+https://github.com/aprioriinvestments/typed_python.git@a881199bbc1171a43f71909ad85f5949662cb67b#egg=typed_python-999.999.999"
]
